languages:
  Ruby: true
  JavaScript: true
  PHP: false
  Python: false

engines:
  brakeman:      # security
    enabled: true
  bundler-audit: # security
    enabled: true
  coffeelint:    # Coffeescript
    enabled: true
  csslint:       # CSS
    enabled: true
  eslint:        # Javascript
    enabled: true
  fixme:         # TODOs
    enabled: true
  markdownlint:  # Markdown
    enabled: true
  reek:          # Ruby: Code smell
    enabled: true
  rubocop:       # Ruby
    enabled: true
  scss-lint:     # SCSS
    enabled: true
  shellcheck:    # Shell scripts
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript

ratings:
  paths:
  - app/**
  - lib/**
  - test/**
  - "**.coffee"
  - "**.css"
  - "**.js"
  - "**.md"
  - "**.rb"
  - "**.scss"
  - "**.sh"
  - Gemfile.lock
